# Generated by Django 3.2.7 on 2021-09-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210927_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(blank=True, null=True, verbose_name='Основной раздел?'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='to_delete',
            field=models.BooleanField(blank=True, null=True, verbose_name='Удалить?'),
        ),
    ]
